import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { API_URL } from "../utils/urls";

export default function Home({ boards}) {
  console.log (boards);

  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.container}>
      {boards.map((board)=> (

        <div className='board'>
          <div className={styles.model}>
            <h2> {board.model} </h2>
          </div>

          <div className={styles.short_description}>
            <h3> {board.short_description} </h3>
          </div>


        </div>


        ))}

    </div>
    </>

  )
}

export async function getStaticProps() {
  const product_res = await fetch(`${API_URL}/boards/`);
  const boards = await product_res.json();
  return {
    props: {
      boards,
    },
  };
}
